import type { Question } from "@/types/assessment.types";

export const cloudSetupQuestions: Question[] = [
  {
    id: "cs_01",
    sectionId: "cloud_setup",
    type: "single_choice",
    text: "How is Identity and Access Management (IAM) configured for your cloud accounts?",
    helpText: "Consider root account usage, least-privilege policies, and role separation.",
    riskWeight: 0.18,
    options: [
      { id: "cs_01_a", label: "Root account used for daily operations, no MFA", weight: 0.0 },
      { id: "cs_01_b", label: "Some IAM users but no role-based access control", weight: 0.25 },
      { id: "cs_01_c", label: "IAM roles and groups defined, MFA on root only", weight: 0.55 },
      { id: "cs_01_d", label: "Full RBAC, MFA enforced on all accounts, least-privilege", weight: 1.0 },
    ],
  },
  {
    id: "cs_02",
    sectionId: "cloud_setup",
    type: "single_choice",
    text: "What network segmentation do you have in place?",
    helpText: "VPCs, subnets, security groups, and firewall rules.",
    riskWeight: 0.14,
    options: [
      { id: "cs_02_a", label: "Everything in one flat network / public subnet", weight: 0.0 },
      { id: "cs_02_b", label: "Basic VPC but limited subnet separation", weight: 0.3 },
      { id: "cs_02_c", label: "Public/private subnets with security groups", weight: 0.7 },
      { id: "cs_02_d", label: "Full network segmentation, WAF, private subnets only for data", weight: 1.0 },
    ],
  },
  {
    id: "cs_03",
    sectionId: "cloud_setup",
    type: "single_choice",
    text: "How are cloud backups and disaster recovery managed?",
    riskWeight: 0.14,
    options: [
      { id: "cs_03_a", label: "No automated backups", weight: 0.0 },
      { id: "cs_03_b", label: "Occasional manual backups", weight: 0.2 },
      { id: "cs_03_c", label: "Automated daily backups, untested restore", weight: 0.6 },
      { id: "cs_03_d", label: "Automated backups, tested DR plan with RTO/RPO defined", weight: 1.0 },
    ],
  },
  {
    id: "cs_04",
    sectionId: "cloud_setup",
    type: "boolean",
    text: "Is your cloud infrastructure defined and managed using Infrastructure-as-Code (IaC)?",
    helpText: "e.g., Terraform, Pulumi, AWS CDK, CloudFormation",
    riskWeight: 0.12,
  },
  {
    id: "cs_05",
    sectionId: "cloud_setup",
    type: "single_choice",
    text: "What cloud audit logging and monitoring is enabled?",
    riskWeight: 0.14,
    options: [
      { id: "cs_05_a", label: "No audit logging enabled", weight: 0.0 },
      { id: "cs_05_b", label: "Basic logging on some services", weight: 0.3 },
      { id: "cs_05_c", label: "CloudTrail/Audit Logs enabled, stored in S3/GCS", weight: 0.65 },
      { id: "cs_05_d", label: "Full audit logging, centralized SIEM with alerting", weight: 1.0 },
    ],
  },
  {
    id: "cs_06",
    sectionId: "cloud_setup",
    type: "single_choice",
    text: "How are production environment changes controlled?",
    riskWeight: 0.12,
    options: [
      { id: "cs_06_a", label: "Direct console/CLI access by anyone on the team", weight: 0.0 },
      { id: "cs_06_b", label: "Limited team members have production access", weight: 0.35 },
      { id: "cs_06_c", label: "Changes via CI/CD only, manual approval gates", weight: 0.75 },
      { id: "cs_06_d", label: "Immutable infrastructure, all changes via code review + CI/CD", weight: 1.0 },
    ],
  },
  {
    id: "cs_07",
    sectionId: "cloud_setup",
    type: "multi_choice",
    text: "Which cloud security services/tools are actively used?",
    helpText: "Select all that apply.",
    riskWeight: 0.10,
    options: [
      { id: "cs_07_a", label: "AWS GuardDuty / GCP Security Command Center / Azure Defender", weight: 0.25 },
      { id: "cs_07_b", label: "Cloud-native CSPM (Prisma, Wiz, AWS Security Hub)", weight: 0.25 },
      { id: "cs_07_c", label: "Container registry scanning", weight: 0.25 },
      { id: "cs_07_d", label: "None of the above", weight: 0.0 },
    ],
  },
  {
    id: "cs_08",
    sectionId: "cloud_setup",
    type: "scale",
    text: "How confident are you in your ability to recover from a complete region outage?",
    riskWeight: 0.16,
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { min: "Not prepared at all", max: "Multi-region, fully automated failover" },
  },
];
