import type { Question } from "@/types/assessment.types";

export const complianceReadinessQuestions: Question[] = [
  {
    id: "cr_01",
    sectionId: "compliance_readiness",
    type: "single_choice",
    text: "Has your company performed a formal data classification exercise?",
    helpText: "Identifying what data you store, its sensitivity level, and data flows.",
    riskWeight: 0.16,
    options: [
      { id: "cr_01_a", label: "No, we have no idea what data we hold or its sensitivity", weight: 0.0 },
      { id: "cr_01_b", label: "Informal understanding, not documented", weight: 0.25 },
      { id: "cr_01_c", label: "Data inventory exists, partially documented", weight: 0.6 },
      { id: "cr_01_d", label: "Full data classification, documented data flows and retention policies", weight: 1.0 },
    ],
  },
  {
    id: "cr_02",
    sectionId: "compliance_readiness",
    type: "single_choice",
    text: "How does your product handle PII and GDPR/CCPA obligations?",
    riskWeight: 0.17,
    options: [
      { id: "cr_02_a", label: "We collect PII with no compliance consideration", weight: 0.0 },
      { id: "cr_02_b", label: "Basic privacy policy exists but no enforcement", weight: 0.2 },
      { id: "cr_02_c", label: "GDPR-aware: consent flows, data deletion on request", weight: 0.7 },
      { id: "cr_02_d", label: "Full compliance program: DPA, data mapping, legal basis for all processing", weight: 1.0 },
    ],
  },
  {
    id: "cr_03",
    sectionId: "compliance_readiness",
    type: "boolean",
    text: "Do you have a publicly accessible and up-to-date privacy policy?",
    riskWeight: 0.10,
  },
  {
    id: "cr_04",
    sectionId: "compliance_readiness",
    type: "single_choice",
    text: "What is your current SOC 2 or ISO 27001 compliance status?",
    riskWeight: 0.18,
    options: [
      { id: "cr_04_a", label: "Not started, no awareness of what it requires", weight: 0.0 },
      { id: "cr_04_b", label: "Aware of requirements, planning to start within 12 months", weight: 0.3 },
      { id: "cr_04_c", label: "SOC 2 Type I completed or in progress", weight: 0.7 },
      { id: "cr_04_d", label: "SOC 2 Type II certified or ISO 27001 certified", weight: 1.0 },
    ],
  },
  {
    id: "cr_05",
    sectionId: "compliance_readiness",
    type: "single_choice",
    text: "How do you assess the security posture of your third-party vendors and SaaS tools?",
    riskWeight: 0.13,
    options: [
      { id: "cr_05_a", label: "No vendor assessment process", weight: 0.0 },
      { id: "cr_05_b", label: "We use only well-known vendors with no formal review", weight: 0.3 },
      { id: "cr_05_c", label: "Vendor questionnaires or SOC 2 review before onboarding", weight: 0.75 },
      { id: "cr_05_d", label: "Formal vendor risk management program with annual reviews", weight: 1.0 },
    ],
  },
  {
    id: "cr_06",
    sectionId: "compliance_readiness",
    type: "boolean",
    text: "Do you have signed Data Processing Agreements (DPAs) with all vendors who process customer data?",
    riskWeight: 0.10,
  },
  {
    id: "cr_07",
    sectionId: "compliance_readiness",
    type: "multi_choice",
    text: "Which regulatory frameworks apply to your business?",
    helpText: "Select all that apply.",
    riskWeight: 0.08,
    options: [
      { id: "cr_07_a", label: "GDPR (EU customers)", weight: 0.25 },
      { id: "cr_07_b", label: "HIPAA (healthcare data)", weight: 0.25 },
      { id: "cr_07_c", label: "PCI-DSS (payment card data)", weight: 0.25 },
      { id: "cr_07_d", label: "None — we have no specific regulatory obligations", weight: 0.0 },
    ],
  },
  {
    id: "cr_08",
    sectionId: "compliance_readiness",
    type: "scale",
    text: "How prepared is your company to respond to a customer data subject access request (DSAR)?",
    riskWeight: 0.08,
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { min: "Completely unprepared", max: "Automated DSAR portal, <30 day SLA" },
  },
];
