import type { Question } from "@/types/assessment.types";

export const securityPracticesQuestions: Question[] = [
  {
    id: "sp_01",
    sectionId: "security_practices",
    type: "single_choice",
    text: "How are application secrets (API keys, DB credentials, tokens) managed?",
    helpText: "e.g., environment variables, secrets managers, hardcoded in code",
    riskWeight: 0.18,
    options: [
      { id: "sp_01_a", label: "Secrets hardcoded in source code or committed to git", weight: 0.0 },
      { id: "sp_01_b", label: "Stored in .env files, not version controlled", weight: 0.3 },
      { id: "sp_01_c", label: "Environment variables injected at deploy time", weight: 0.6 },
      { id: "sp_01_d", label: "Dedicated secrets manager (AWS Secrets Manager, Vault, etc.) with rotation", weight: 1.0 },
    ],
  },
  {
    id: "sp_02",
    sectionId: "security_practices",
    type: "single_choice",
    text: "How frequently do you scan for vulnerabilities in dependencies and containers?",
    riskWeight: 0.14,
    options: [
      { id: "sp_02_a", label: "Never", weight: 0.0 },
      { id: "sp_02_b", label: "Manually when a major issue is reported", weight: 0.2 },
      { id: "sp_02_c", label: "Automated scanning in CI pipeline", weight: 0.75 },
      { id: "sp_02_d", label: "Continuous scanning + alerting + SLA for remediation", weight: 1.0 },
    ],
  },
  {
    id: "sp_03",
    sectionId: "security_practices",
    type: "single_choice",
    text: "Have you conducted any penetration testing or security audits?",
    riskWeight: 0.15,
    options: [
      { id: "sp_03_a", label: "Never", weight: 0.0 },
      { id: "sp_03_b", label: "Internal review only, no external testing", weight: 0.25 },
      { id: "sp_03_c", label: "External pen test done once", weight: 0.65 },
      { id: "sp_03_d", label: "Regular annual pen tests + bug bounty program", weight: 1.0 },
    ],
  },
  {
    id: "sp_04",
    sectionId: "security_practices",
    type: "boolean",
    text: "Do you have a documented Incident Response (IR) plan?",
    helpText: "Including defined roles, escalation paths, and communication templates.",
    riskWeight: 0.13,
  },
  {
    id: "sp_05",
    sectionId: "security_practices",
    type: "single_choice",
    text: "How is data encryption handled in your application?",
    riskWeight: 0.14,
    options: [
      { id: "sp_05_a", label: "No encryption in transit or at rest", weight: 0.0 },
      { id: "sp_05_b", label: "HTTPS for transit only", weight: 0.35 },
      { id: "sp_05_c", label: "Encryption in transit and at rest for most data", weight: 0.75 },
      { id: "sp_05_d", label: "E2E encryption, envelope encryption, key management via KMS", weight: 1.0 },
    ],
  },
  {
    id: "sp_06",
    sectionId: "security_practices",
    type: "multi_choice",
    text: "Which application security practices are in place?",
    helpText: "Select all that apply.",
    riskWeight: 0.12,
    options: [
      { id: "sp_06_a", label: "SAST (static analysis) in CI/CD", weight: 0.25 },
      { id: "sp_06_b", label: "DAST (dynamic analysis / runtime scanning)", weight: 0.25 },
      { id: "sp_06_c", label: "Dependency license & security audits (e.g., Snyk, Dependabot)", weight: 0.25 },
      { id: "sp_06_d", label: "None of the above", weight: 0.0 },
    ],
  },
  {
    id: "sp_07",
    sectionId: "security_practices",
    type: "single_choice",
    text: "How is employee offboarding handled in terms of access revocation?",
    riskWeight: 0.07,
    options: [
      { id: "sp_07_a", label: "No formal process, accounts left active", weight: 0.0 },
      { id: "sp_07_b", label: "Ad-hoc, happens within days/weeks", weight: 0.3 },
      { id: "sp_07_c", label: "Same-day revocation, checklist exists", weight: 0.75 },
      { id: "sp_07_d", label: "Automated deprovisioning tied to HR system", weight: 1.0 },
    ],
  },
  {
    id: "sp_08",
    sectionId: "security_practices",
    type: "scale",
    text: "How mature is your security awareness training for engineers?",
    riskWeight: 0.07,
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { min: "No training at all", max: "Regular mandatory training + phishing simulations" },
  },
];
