import type { Question } from "@/types/assessment.types";

export const teamMaturityQuestions: Question[] = [
  {
    id: "tm_01",
    sectionId: "team_maturity",
    type: "single_choice",
    text: "How mature is your CI/CD pipeline?",
    helpText: "From code commit to production deployment.",
    riskWeight: 0.16,
    options: [
      { id: "tm_01_a", label: "No CI/CD — manual deployments", weight: 0.0 },
      { id: "tm_01_b", label: "Basic CI (tests run on PR), manual deploys", weight: 0.35 },
      { id: "tm_01_c", label: "Full CI/CD with automated staging deploys, manual prod approval", weight: 0.75 },
      { id: "tm_01_d", label: "Fully automated deployments with rollback, feature flags, canary", weight: 1.0 },
    ],
  },
  {
    id: "tm_02",
    sectionId: "team_maturity",
    type: "single_choice",
    text: "What observability tooling does your production system have?",
    riskWeight: 0.15,
    options: [
      { id: "tm_02_a", label: "No monitoring or logging", weight: 0.0 },
      { id: "tm_02_b", label: "Basic uptime monitoring only", weight: 0.2 },
      { id: "tm_02_c", label: "Logs + metrics + basic alerting (e.g., Datadog, CloudWatch)", weight: 0.65 },
      { id: "tm_02_d", label: "Full observability: structured logs, distributed tracing, APM, SLOs", weight: 1.0 },
    ],
  },
  {
    id: "tm_03",
    sectionId: "team_maturity",
    type: "boolean",
    text: "Is there an on-call rotation with defined escalation paths for production incidents?",
    riskWeight: 0.12,
  },
  {
    id: "tm_04",
    sectionId: "team_maturity",
    type: "single_choice",
    text: "What is your code review process?",
    riskWeight: 0.13,
    options: [
      { id: "tm_04_a", label: "No code review, direct commits to main", weight: 0.0 },
      { id: "tm_04_b", label: "Reviews happen sometimes, not enforced", weight: 0.25 },
      { id: "tm_04_c", label: "Required reviews for all PRs before merge", weight: 0.75 },
      { id: "tm_04_d", label: "Required reviews + automated security/lint checks + approval gates", weight: 1.0 },
    ],
  },
  {
    id: "tm_05",
    sectionId: "team_maturity",
    type: "scale",
    text: "What percentage of your codebase has automated test coverage?",
    riskWeight: 0.12,
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: { min: "0% — no tests at all", max: "80%+ coverage with integration tests" },
  },
  {
    id: "tm_06",
    sectionId: "team_maturity",
    type: "single_choice",
    text: "How does your team manage technical debt and security vulnerabilities in the backlog?",
    riskWeight: 0.11,
    options: [
      { id: "tm_06_a", label: "No tracking, addressed only when they cause issues", weight: 0.0 },
      { id: "tm_06_b", label: "Tracked informally, low priority", weight: 0.3 },
      { id: "tm_06_c", label: "Dedicated backlog, addressed in quarterly sprints", weight: 0.7 },
      { id: "tm_06_d", label: "SLA-driven remediation with severity tiers", weight: 1.0 },
    ],
  },
  {
    id: "tm_07",
    sectionId: "team_maturity",
    type: "boolean",
    text: "Does your team conduct post-mortems (blameless) after production incidents?",
    riskWeight: 0.10,
  },
  {
    id: "tm_08",
    sectionId: "team_maturity",
    type: "single_choice",
    text: "How is access to production systems managed across team members?",
    riskWeight: 0.11,
    options: [
      { id: "tm_08_a", label: "Shared credentials, anyone can access production", weight: 0.0 },
      { id: "tm_08_b", label: "Individual accounts but broad production access", weight: 0.3 },
      { id: "tm_08_c", label: "Role-based access, engineers have limited prod access", weight: 0.7 },
      { id: "tm_08_d", label: "Just-in-time access, full audit trail, no standing prod permissions", weight: 1.0 },
    ],
  },
];
